language: node_js
node_js:
  - '16'

before_install:
  - npm install -g @angular/cli
  - gem install faraday -v 1.9.3
  - gem install dpl-heroku -v 1.10.17.travis.6637.6

install: npm install

branches:
  only:
    - master

deploy:
  provider: heroku
  app: initial-klets
  api_key:
    secure: "1af0d7eb-bab4-41da-b68c-db438b252c69"
