language: node_js
node_js:
  - '12'

before_install:
  - npm install -g @angular/cli
install: npm install

branches:
  only:
    - master

before_script:
  apt-get update -qy
  apt-get install -y ruby-dev
  gem install dpl --pre
  gem install bundler
  yarn install


deploy:
  provider: heroku
  app: initial-klets
  api_key:
    secure: "1af0d7eb-bab4-41da-b68c-db438b252c69"
