language: node_js
node_js:
  - '16'

before_install:
  - npm install -g @angular/cli
install: npm install

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0


branches:
  only:
    - master

deploy:
  provider: heroku
  app: initial-klets
  api_key:
    secure: "1af0d7eb-bab4-41da-b68c-db438b252c69"
