language: node_js
node_js:
  - '12'

before_install:
  - npm install -g @angular/cli
  - gem install faraday -v 1.9.3
install: npm install

branches:
  only:
    - master

deploy:
  provider: heroku
  app: initial-klets
  api_key:
    secure: "1af0d7eb-bab4-41da-b68c-db438b252c69"
